# "pitch" - Licensed under the MIT LICENSE (see /LICENSE)
#                             _        _
#                            /@\——————/@\
# .———  .                   |   o    o   |     .————      .            .
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   .
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   |
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |
#                 |        \              /                              __/
#                           ¯————————————¯

[package]
name = "pitch"
version = "0.1.1"
authors = [
	"Jeron A. Lau <jeron.lau@plopgrizzly.com>",
]

license = "MIT"
documentation = "https://docs.rs/pitch"
homepage = "http://plopgrizzly.com/audio"
repository = "https://gitlab.com/plopgrizzly/audio/pitch"

readme = "readme.md"
description = "Quickly and accurately determine the pitch and volume of a sound sample."
keywords = ["bcf", "bacf", "acf", "auto-correlation", "detection"]
categories = ["algorithms", "multimedia::audio"]

[dependencies]

[dev-dependencies]
byteorder = "1.2"
