# "pitch" - Licensed under the MIT LICENSE (see /LICENSE)
#                             _        _
#                            /@\——————/@\
# .———  .                   |   o    o   |     .————      .            .
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   .
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   |
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |
#                 |        \              /                              __/
#                           ¯————————————¯

[package]
name = "pitch"
version = "0.1.0"
authors = [
	"Jeron A. Lau <jeron.lau@plopgrizzly.com>",
]

license = "MIT"
documentation = "https://doc.plopgrizzly.com/pitch"
homepage = "http://plopgrizzly.com/audio"
repository = "https://gitlab.com/plopgrizzly/audio/pitch"

readme = "readme.md"
description = "Quickly and accurately determine the pitch and volume of a sound sample."
keywords = [
	"bcf", "bacf", "acf", "auto-correlation", "detection"
]
categories = ["algorithms", "multimedia::audio"]

exclude = [
	"examples/*", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", ".gitignore",
	"_config.yml", "ISSUE_TEMPLATE.md", "icon.png", "icon.ico"
]

[dependencies]

[dev-dependencies]
byteorder = "1.2"
